# Generated by Django 4.2.7 on 2023-12-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Contact', models.FloatField()),
                ('dept', models.CharField(max_length=100)),
                ('cat', models.IntegerField()),
                ('pimage', models.ImageField(upload_to='image')),
                ('Description', models.CharField(max_length=500)),
            ],
        ),
    ]
