# Generated by Django 4.2.7 on 2023-12-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept',
            field=models.CharField(choices=[(1, 'Dermatologists'), (2, 'Cardiologists'), (3, 'Neurologist'), (4, 'General Physician')], max_length=100),
        ),
    ]
