# Generated by Django 4.2.7 on 2023-12-22 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0003_department_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='cat',
        ),
    ]
