# Generated by Django 4.2.7 on 2023-12-22 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0004_remove_department_cat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
