# Generated by Django 5.0 on 2023-12-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pdetails',
            field=models.CharField(max_length=500, verbose_name='Product Details'),
        ),
    ]
