# Generated by Django 5.0 on 2023-12-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0007_alter_product_pdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='product name'),
        ),
    ]
