# Generated by Django 5.0 on 2023-12-26 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0010_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('dept1', 'Cardiology'), ('dept2', 'Neurology'), ('dept3', 'Hepatology'), ('dept4', 'General Physician')], max_length=20)),
                ('doctor', models.CharField(choices=[('doctor1', 'Jhon Jackson'), ('doctor2', 'Amy Jacob'), ('doctor3', 'Jing Who'), ('doctor4', 'Jane Anderson'), ('doctor5', 'Ricky Nathan'), ('doctor6', 'Nelson John'), ('doctor7', 'Patrick Shiong'), ('doctor8', 'Solange Falade')], default='doctor8', max_length=20)),
                ('is_active', models.BooleanField(default=True, verbose_name='Available')),
            ],
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('department', models.CharField(choices=[('dept1', 'Cardiology'), ('dept2', 'Neurology'), ('dept3', 'Hepatology'), ('dept4', 'General Physician')], max_length=20)),
                ('doctor', models.CharField(choices=[('doctor1', 'Jhon Jackson'), ('doctor2', 'Amy Jacob'), ('doctor3', 'Jing Who'), ('doctor4', 'Jane Anderson'), ('doctor5', 'Ricky Nathan'), ('doctor6', 'Nelson John'), ('doctor7', 'Patrick Shiong'), ('doctor8', 'Solange Falade')], max_length=20)),
                ('message', models.TextField(default=' ')),
                ('aid', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
