# Generated by Django 5.0 on 2023-12-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0011_department_appointments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
                ('uemail', models.CharField(max_length=50)),
                ('ucmts', models.CharField(max_length=200)),
                ('rating', models.CharField(choices=[('bad', 'bad '), ('good', 'good'), ('excellent', 'excellent')], max_length=20)),
            ],
        ),
    ]
